const double GROUND_BOTTOM_MARGIN = 10.2,
    DINO_LEFT_MARGIN = 30.0,
    DINO_VIEWPORT_HEIGHT = 50.0,
    DINO_VIEWPORT_WIDTH = 50.0,
    OBSTACLE_VIEWPORT_HEIGHT = 30.0,
    OBSTACLE_VIEWPORT_WIDTH = 30.0;

int OBSTACLE_MAX_OFFSET = 10, OBSTACLE_MIN_OFFSET = 5;
